language: ruby
rvm: 2.0.0
before_script: sh travis.sh
after_success: bundle exec rake release
env:
  global:
  - secure: X7O72TfIYuf2FvirV0AdfmzP+8bmkR4Cu2v6CBU9R1DpcyEgtYRflZSpYsB6pb0QwSNrLPhp5pbKXpSxDR+t8l9Th3YO8jeNKg2kFr05cvSM8yFbUsUO72nPZin9eespQHt6wM/Z2kFfDxHpEF238dsb3RNsA+N41O1DdBIc9lY=
  - secure: RniLvX2sCB7hLF8Fzl4olWu3J88gX2vQEQGY2nuy+wLaPMNBz65WWBQ4lqn9ZZuD/brjhAxcg8qfPmUXJ8UsfDlriIiZ3IF7ZnVz9434YWuE2Pq/hT1NjEgs2a3cxnyPYKCv5CyLPtSAqENfQF1RyZ1WlZvisdg3y+8l4EbgI7M=
  - secure: DA4X32fRPzLJUPzSGEtF3yxK9GVLUoZ4GWaTcG/jse+Ivou3wlGBYclbEOfGuiA9mV1W014gIJ+LrC+wPGIYJoxdBX9CjqjqoGYlenY75+Ysbm2CqSjkWMF5WoOcqi8vn+sffyL0Wj3Sbw42RZnGD5CoByU4vrkfpdxau5fwnBw=
notifications:
  hipchat:
    rooms:
      secure: TqNWeWCexwfDYni1dFZy8NHdFCdBB9xpD3d/mPFjJj5DoDMuDzJYcsp6t4Iv0ICLCg4SiLLgxg6d22K9EdLvaqVzNNiGG5goYvUiv9pjDyEzSl+usX0ABr7IHB7ukmPPPUWKeQ7IY6bsMkKpb2PRVP82Eq1WFA4zsaGJhrmWAzw=
    format: html
    template: Build <a href="%{build_url}">#%{build_number}</a> for <a href="https://github.com/%{repository}/tree/%{branch}">%{branch}</a>
      of <a href="https://github.com/%{repository}">%{repository}</a> %{result} in
      %{duration}. (<a href="%{compare_url}">changes</a>)
